name: mattermost-client-ogra
version: '0.3'
summary: Webapp for Mattermost
description: |
  Single server, low profile electron webapp to chat on mattermost with tray
  icon and unread message count in dock icons.

  The snap comes with a mattermost-client-ogra.reset command that un-sets the
  picked server and allows you to switch to a new one.
base: core24
confinement: strict
grade: stable
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  mattermost-client-ogra:
    extensions: [gnome]
    command: electron/mattermost-client-ogra --disable-gpu --no-sandbox
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - audio-playback
      - audio-record
      - home
      - network
      - unity7
      - shmem

  reset:
    extensions: [gnome]
    command: electron/mattermost-client-ogra --disable-gpu --no-sandbox --reset
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - audio-record
      - audio-playback
      - home
      - network
      - unity7
      - shmem

plugs:
  shmem:
    interface: shared-memory
    private: true

parts:
  client:
    plugin: nil
    source: ./electron
    build-environment:
      - PATH: "$PATH:$SNAPCRAFT_PART_BUILD/node_modules/.bin"
    override-build: |
      set +u # core20 base does not allow unbound variables !
      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      npm install
      electron-packager . --overwrite --platform=linux --output=release-build \
          --prune=true --out $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/$SNAPCRAFT_PROJECT_NAME-linux-* \
          $SNAPCRAFT_PART_INSTALL/electron
      cp icons/*.png $SNAPCRAFT_PART_INSTALL/
    build-snaps:
      - node/18/stable
    stage-packages:
      - libasound2
      - libnss3
      - libunity9 # for badgeCount in dock
      - libx11-xcb1
      - libxss1
      - libxtst6
      - libproxy1v5
  cleanup:
    after: [ client ]
    plugin: nil
    build-snaps: [ gnome-46-2404 ]
    override-prime: |
        chmod +rx electron
        set -eux
        cd /snap/gnome-46-2404/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
