name: mattermost-client-ogra
version: '0.3'
summary: Webapp for Mattermost
description: |
  Single server, low profile electron webapp to chat on mattermost with tray
  icon and unread message count in dock icons.

  The snap comes with a mattermost-client-ogra.reset command that un-sets the
  picked server and allows you to switch to a new one.
base: core18
confinement: strict
grade: stable
compression: lzo

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  mattermost-client-ogra:
    extensions: [gnome-3-34]
    command: electron/mattermost-client-ogra --disable-gpu --no-sandbox
    environment:
      DISABLE_WAYLAND: 1
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - audio-playback
      - audio-record
      - browser-support
      - desktop
      - gsettings
      - home
      - network
      - network-bind
      - opengl
      - unity7
      - wayland
      - x11
  reset:
    extensions: [gnome-3-34]
    command: electron/mattermost-client-ogra --disable-gpu --no-sandbox --reset
    environment:
      DISABLE_WAYLAND: 1
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - audio-playback
      - audio-record
      - browser-support
      - desktop
      - gsettings
      - home
      - network
      - network-bind
      - opengl
      - unity7
      - wayland
      - x11

parts:
  client:
    plugin: nil
    source: ./electron
    build-environment:
      - PATH: "$PATH:$SNAPCRAFT_PART_BUILD/node_modules/.bin"
    override-build: |
      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      npm install
      electron-packager . --overwrite --platform=linux --output=release-build \
          --prune=true --out $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/$SNAPCRAFT_PROJECT_NAME-linux-* \
          $SNAPCRAFT_PART_INSTALL/electron
      cp icons/*.png $SNAPCRAFT_PART_INSTALL/
    build-snaps:
      - node/14/stable
    stage-packages:
      - libasound2
      - libgconf-2-4
      - libnss3
      - libunity9 # for badgeCount in dock
      - libx11-xcb1
      - libxss1
      - libxtst6
  cleanup:
    after: [ client ]
    plugin: nil
    build-snaps: [ gnome-3-34-1804 ]
    override-prime: |
      set -eux
      cd /snap/gnome-3-34-1804/current
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
